[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.test]
cwd = "./build/"
command = "make"
args = [ "test" ]

[tasks.build]
dependencies = [ "cmake" ]
command = "cmake"
args = [ "--build", "build" ]

[tasks.cmake]
command = "cmake"
args = [
    "-S",
    ".",
    "-B",
    "build",
    "-DBUILD_TESTING=ON",
]

[tasks.lint]
command = "cabin"
args = [
    "lint",
    "--exclude", "Catch2",
]

[tasks.fmt-lib]
install_crate = "fd-find"
cwd = "./include/"
command = "fd"
args = [
    "-e", "hpp",
    "-e", "cpp",
    "-x", "clang-format", "-i"
]

[tasks.fmt-test]
install_crate = "fd-find"
cwd = "./test/"
command = "fd"
args = [
    "-e", "hpp",
    "-e", "cpp",
    "-x", "clang-format", "-i"
]

[tasks.fmt]
dependencies = [ "fmt-lib", "fmt-test" ]
 
[tasks.pretty]
dependencies = [
    "fmt",
    "lint",
    "build",
    "test"
]
