[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.test]
cwd = "./build/"
command = "make"
args = [ "test" ]

[tasks.build]
dependencies = [ "cmake" ]
command = "cmake"
args = [ "--build", "build" ]

[tasks.cmake]
command = "cmake"
args = [
    "-S",
    ".",
    "-B",
    "build",
    "-DBUILD_TESTING=ON",
]

[tasks.lint-lib]
cwd = "./include/"
command = "poac"
args = [ "lint" ]

[tasks.lint-test]
cwd = "./test/"
command = "poac"
args = [ "lint" ]

[tasks.fmt-lib]
cwd = "./include/"
command = "poac"
args = [ "fmt" ]

[tasks.fmt-test]
cwd = "./test/"
command = "poac"
args = [ "fmt" ]

[tasks.pretty]
dependencies = [
    "fmt-lib",
    "fmt-test",
    "lint-lib",
    "build",
    "test"
]
