site_name: Mitama.Result User Manual
site_dir: '../docs/'

# Project information
site_name: Mitama.Result | User Manual
site_description: Mitama.Result C++17 Library
site_author: mitama
site_url: https://loligothick.github.io/mitama-cpp-result/

# Repository
repo_name: loligothick/mitama-cpp-result
repo_url: https://github.com/loligothick/mitama-cpp-result
edit_uri: ""

# Theme
theme:
  name: 'material'
  language: 'en'
  logo:
    icon: 'donut_small'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/mitama_rs'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - mdx_math:
      enable_dollar_delimiter: true
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: True
      separator: "_"
      baselevel: 1

extra_javascript: 
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - cppmap_styles.css
# Page tree

nav:
  - Home: README.md
  - maybe:
    - Maybe 101: maybe/intro.md
    - Special Members: maybe/special_members.md
    - API Reference: maybe/APIs.md
    - Comparisons: maybe/comparisons.md # TODO
    - Meta Functions: maybe/metafunctions.md
    - "": maybe/_Internal/comparisons.md
    - "": maybe/_APIs/is_just.md
    - "": maybe/_APIs/is_nothing.md
    - "": maybe/_APIs/as_ref.md
    - "": maybe/_APIs/expect.md
    - "": maybe/_APIs/unwrap.md
    - "": maybe/_APIs/unwrap_or.md
    - "": maybe/_APIs/unwrap_or_else.md
    - "": maybe/_APIs/map.md
    - "": maybe/_APIs/map_or.md
    - "": maybe/_APIs/map_or_else.md
    - "": maybe/_APIs/map_anything_else.md
    - "": maybe/_APIs/ok_or.md
    - "": maybe/_APIs/ok_or_else.md
    - "": maybe/_APIs/conj.md
    - "": maybe/_APIs/and_then.md
    - "": maybe/_APIs/filter.md
    - "": maybe/_APIs/disj.md
    - "": maybe/_APIs/or_else.md
    - "": maybe/_APIs/get_or_emplace.md
    - "": maybe/_APIs/get_or_emplace_with.md
    - "": maybe/_APIs/replace.md
    - "": maybe/_APIs/replace_with.md
    - "": maybe/_APIs/cloned.md
    - "": maybe/_APIs/unwrap_or_default.md
    - "": maybe/_APIs/transpose.md
    - "": maybe/_APIs/flatten.md
    - "": maybe/_APIs/and_finally.md
    - "": maybe/_APIs/or_finally.md
    - "": maybe/_APIs/and_peek.md
    - "": maybe/_APIs/or_peek.md
  - result:
    - Result 101: result/intro.md
    - Special Members: result/special_members.md
    - APIs: result/APIs.md
    - Meta Functions: result/metafunctions.md
    - Comparisons: result/comparisons.md
    - CHANGELOG: result/_APIs/README.md
    - "": result/_APIs/is_ok.md
    - "": result/_APIs/is_err.md
    - "": result/_APIs/ok.md
    - "": result/_APIs/err.md
    - "": result/_APIs/map.md
    - "": result/_APIs/map_or_else.md
    - "": result/_APIs/map_err.md
    - "": result/_APIs/conj.md
    - "": result/_APIs/and_then.md
    - "": result/_APIs/disj.md
    - "": result/_APIs/or_else.md
    - "": result/_APIs/unwrap_or.md
    - "": result/_APIs/unwrap_or_else.md
    - "": result/_APIs/unwrap.md
    - "": result/_APIs/unwrap_err.md
    - "": result/_APIs/unwrap_or_default.md
    - "": result/_APIs/transpose.md
    - "": result/_metafunctions/is_result.md
    - "": result/_metafunctions/is_result_with.md
    - "": result/_APIs/and_finally.md
    - "": result/_APIs/or_finally.md
    - "": result/_APIs/and_peek.md
    - "": result/_APIs/or_peek.md
