version: 2
jobs:
  clang_7_0_0:
    working_directory: /mitama-cpp-result
    docker:
      - image: enumack/mitama-env:clang-7.0.0
    steps:
      - checkout
      - run: ls
      - run: cmake --version
      - run: cmake . && make && ctest --no-label-summary

workflows:
  version: 2
  build_and_test:
    jobs:
      # GCC
      # Clang
      - clang_7_0_0