version: 2
jobs:
  gcc_HEAD:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-head --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_8_2_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-8.2.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_8_1_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-8.1.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_7_3_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-7.3.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_7_2_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-7.2.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_7_1_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-7.1.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_6_3_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-6.3.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_6_2_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-6.2.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_6_1_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-6.1.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_5_5_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-5.5.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_5_4_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-5.4.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_5_3_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-5.3.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_5_2_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-5.2.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  gcc_5_1_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=gcc-5.1.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  clang_HEAD:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=clang-head --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  clang_7_0_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=clang-7.0.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  clang_6_0_1:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=clang-6.0.1 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results 
  clang_6_0_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=clang-6.0.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  clang_5_0_0:
    working_directory: /mitama-cpp-result
    environment:
      TEST_RESULTS: /results
    docker:
      - image: buildpack-deps:bionic-curl
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp test/Result_Test.cpp --compiler=clang-5.0.0 --std=c++17 --boost=1.65.1
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results

workflows:
  version: 2
  wandbox:
    jobs:
      # GCC
      # - gcc_HEAD [internal compiler error]
      - gcc_8_2_0
      - gcc_8_1_0:
          requires:
            - gcc_8_2_0
      # - gcc_7_3_0: [virtual memory exhausted]
      # - gcc_7_2_0: [virtual memory exhausted]
      - gcc_7_1_0:
          requires:
            - gcc_8_1_0
      # Clang
      - clang_HEAD:
          requires:
            - gcc_7_1_0
      - clang_7_0_0:
          requires:
            - clang_HEAD
      - clang_6_0_1:
          requires:
            - clang_7_0_0
      - clang_6_0_0:
          requires:
            - clang_6_0_1
      # - clang_5_0_0 invoke_result is not supported
