version: 2.1
executors:
  default:
    docker:
      - image: buildpack-deps:bionic-curl
  test-env:
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    docker:
      - image: enumack/mitama-env:<< parameters.compiler >>

jobs:
  test:
    description: Testing the library using Catch2
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    executor:
      name: test-env
      compiler: << parameters.compiler >>
    steps:
      - checkout
      - run: apt upgrade -y && apt update -y && apt install -y git
      - run: git submodule update --init --recursive
      - run: ./build_and_test.sh

workflows:
  build:
    jobs:
      - test:
          compiler: gcc-head-20200808
