version: 2
jobs:
  clang_7_0_0:
    working_directory: /mitama-cpp-result
    docker:
      - image: circleci/golang:1.11-stretch
    steps:
      - checkout
      - run: curl https://github.com/LoliGothick/cbt/releases/download/v0.5.0/cbt_linux_amd64.zip
      - run: tar -zxvf ./cbt_linux_amd64.zip
      - run: chmod +x ./cbt
      - run: cbt wandbox cpp test/Result_Test.cpp --compiler=clang-7.0.0 --std=c++17 --boost=1.66.0 
workflows:
  version: 2
  build_and_test:
    jobs:
      # GCC
      # Clang
      - clang_7_0_0