version: 2.1
executors:
  default:
    docker:
      - image: buildpack-deps:bionic-curl
  test-env:
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    docker:
      - image: enumack/mitama-env:<< parameters.compiler >>

jobs:
  full-test:
    description: Testing the library using Catch2
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    executor:
      name: test-env
      compiler: << parameters.compiler >>
    steps:
      - checkout
      - run: apt upgrade -y && apt update -y && apt install -y git
      - run: git submodule update --init --recursive
      - run: mkdir build && cd build && cmake .. &&  make && ./tests

workflows:
  build:
    jobs:
      - full-test:
          compiler: clang-7.0.1
      - full-test:
          compiler: clang-7.0.0
      - full-test:
          compiler: clang-8.0.0
      - full-test:
          compiler: gcc-8.3
      - full-test:
          compiler: gcc-8.2
      - full-test:
          compiler: gcc-8.1
      - full-test:
          compiler: gcc-7.3
      - full-test:
          compiler: gcc-7.2
      - full-test:
          compiler: gcc-7.1
