name: Deploy Documets with MkDocs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs'

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Git config
        run: |
          git config --global core.symlinks true
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com

      # リポジトリをチェックアウトする
      # MkDocsでgit-revision-dateプラグインを利用している場合は、
      # 全てのコミット履歴をfetchする(fetch-depth: 0)
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Python3.8をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      # poetry.lockのハッシュ値が一致する場合は、
      # 以前に実行した際のキャッシュを復元する
      - name: Get pip cache
        id: cache-pip
        uses: actions/cache@v2
        with:
          path: ~/cache/poetry/
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
            ${{ runner.os }}-poetry-

      # Poetryをインストールする
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::set-env name=PATH::$env:PATH;$HOME/.poetry/bin"

      # poetry.lockから依存関係をインストールする
      - name: Install dependencies
        run: |
          poetry install --no-root

      # pytestでテストを実行する
      - name: Test with pytest
        run: |
          poetry run pytest

      # MkDocsでGitHubへデプロイする
      - name: MkDocs Deploy
        run: |
          git fetch --depth=1 origin master
          poetry run mkdocs gh-deploy
